export const FALLBACK_DATA = {
  projects: [
    {
      id: 'proj_kgm_riyadh_01',
      org_id: 'org_kgm_01',
      property_id: 'prop_kgm_riyadh_01',
      title: 'The Royal Sovereign Villa — Cinematic Showcase',
      status: 'completed',
      video_style: 'kgm_luxury',
      cinematic_style: 'kgm_luxury',
      default_aspect_ratio: '16:9',
      default_duration: 10,
      target_duration_seconds: 100,
      public_id: 'kgm-film-royal-villa-riyadh',
      cover_image_url: '/uploads/villa_01_hero_exterior.jpg',
      audio_track_id: 'mus_lux_01',
      property_name: 'The Royal Sovereign Villa — Al-Malqa',
      location: 'Al-Malqa District, Northern Riyadh, Kingdom of Saudi Arabia',
      price: 14800000,
      currency: 'USD',
      bedrooms: 7,
      bathrooms: 9,
      property_size: '18,500 sq ft (1,720 m²)',
      description: 'An extraordinary architectural statement combining timeless travertine stone, soaring double-height pivot doors, book-matched Italian marble, and an infinity water terrace. Meticulously curated for the discerning collector seeking rare architectural craftsmanship in prime Riyadh.',
      shot_count: 10,
      approved_shot_count: 10,
      created_at: '2026-09-19T01:03:14.298Z',
      updated_at: '2026-09-19T12:57:36.247Z',
    },
  ],
  properties: [
    {
      id: 'prop_kgm_riyadh_01',
      org_id: 'org_kgm_01',
      property_name: 'The Royal Sovereign Villa — Al-Malqa',
      property_ref: 'KGM-RUH-001',
      property_type: 'luxury_villa',
      marketing_objective: 'sale',
      location: 'Al-Malqa District, Northern Riyadh, Kingdom of Saudi Arabia',
      property_status: 'active',
      bedrooms: 7,
      bathrooms: 9,
      property_size: '18,500 sq ft (1,720 m²)',
      price: 14800000,
      currency: 'USD',
      description: 'Ultra-exclusive private estate with monolithic Calacatta marble, smart climate glass, subterranean showroom, and manicured desert oasis gardens.',
      agent_name: 'Faris Al-Saud — Senior Partner',
      agent_contact: 'faris.alsaud@kgm-estates.com',
      agent_whatsapp: '+966 50 123 4567',
      agent_website: 'https://kgm-estates.com/properties/royal-sovereign',
      cta_text: 'Request Confidential Private Viewing',
      cover_image: '/uploads/villa_01_hero_exterior.jpg',
      image_count: 10,
      project_count: 1,
      created_at: '2026-09-19T01:03:14.298Z',
      updated_at: '2026-09-19T12:57:36.247Z',
    },
  ],
  shots: [
    {
      id: 'shot_demo_1',
      project_id: 'proj_kgm_riyadh_01',
      image_id: 'img_demo_1',
      shot_name: 'Hero Exterior Dusk Facade',
      shot_number: 1,
      sequence_order: 1,
      category: 'exterior',
      motion_preset_id: 'preset_hero_exterior',
      camera_movement: 'Dolly In (Forward Axial)',
      camera_direction: 'forward',
      camera_speed: 'slow',
      lens: '24mm',
      lens_focal_length: '24mm',
      duration: 10,
      duration_seconds: 10,
      motion_intensity: 0.25,
      status: 'approved',
      generation_status: 'completed',
      progress: 100,
      provider: 'native_ffmpeg',
      video_url: '/renders/shot_shot_demo_1_master.mp4',
      storage_path: '/uploads/villa_01_hero_exterior.jpg',
    },
    {
      id: 'shot_demo_2',
      project_id: 'proj_kgm_riyadh_01',
      image_id: 'img_demo_2',
      shot_name: 'Grand Entrance Pivot Door & Foyer',
      shot_number: 2,
      sequence_order: 2,
      category: 'entrance',
      motion_preset_id: 'preset_entrance_foyer',
      camera_movement: 'Vertical Jib / Crane Up',
      camera_direction: 'up',
      camera_speed: 'slow',
      lens: '24mm',
      lens_focal_length: '24mm',
      duration: 10,
      duration_seconds: 10,
      motion_intensity: 0.22,
      status: 'approved',
      generation_status: 'completed',
      progress: 100,
      provider: 'native_ffmpeg',
      video_url: '/renders/shot_shot_demo_2_master.mp4',
      storage_path: '/uploads/villa_02_entrance_foyer.jpg',
    },
    {
      id: 'shot_demo_3',
      project_id: 'proj_kgm_riyadh_01',
      image_id: 'img_demo_3',
      shot_name: 'Double-Height Living Salon',
      shot_number: 3,
      sequence_order: 3,
      category: 'living_room',
      motion_preset_id: 'preset_living_glide',
      camera_movement: 'Lateral Tracking (Left to Right)',
      camera_direction: 'right',
      camera_speed: 'slow',
      lens: '28mm',
      lens_focal_length: '28mm',
      duration: 10,
      duration_seconds: 10,
      motion_intensity: 0.20,
      status: 'approved',
      generation_status: 'completed',
      progress: 100,
      provider: 'native_ffmpeg',
      video_url: '/renders/shot_shot_demo_3_master.mp4',
      storage_path: '/uploads/villa_03_living_salon.jpg',
    },
    {
      id: 'shot_demo_4',
      project_id: 'proj_kgm_riyadh_01',
      image_id: 'img_demo_4',
      shot_name: 'Formal Banqueting Salon',
      shot_number: 4,
      sequence_order: 4,
      category: 'dining',
      motion_preset_id: 'preset_dining_sweep',
      camera_movement: 'Slow Diagonal Push',
      camera_direction: 'forward_right',
      camera_speed: 'slow',
      lens: '35mm',
      lens_focal_length: '35mm',
      duration: 10,
      duration_seconds: 10,
      motion_intensity: 0.18,
      status: 'approved',
      generation_status: 'completed',
      progress: 100,
      provider: 'native_ffmpeg',
      video_url: '/renders/shot_shot_demo_4_master.mp4',
      storage_path: '/uploads/villa_04_formal_dining.jpg',
    },
    {
      id: 'shot_demo_5',
      project_id: 'proj_kgm_riyadh_01',
      image_id: 'img_demo_5',
      shot_name: 'Culinary Master Kitchen',
      shot_number: 5,
      sequence_order: 5,
      category: 'kitchen',
      motion_preset_id: 'preset_kitchen_dolly',
      camera_movement: 'Axial Dolly & Shallow Parallax',
      camera_direction: 'forward',
      camera_speed: 'slow',
      lens: '35mm',
      lens_focal_length: '35mm',
      duration: 10,
      duration_seconds: 10,
      motion_intensity: 0.18,
      status: 'approved',
      generation_status: 'completed',
      progress: 100,
      provider: 'native_ffmpeg',
      video_url: '/renders/shot_shot_demo_5_master.mp4',
      storage_path: '/uploads/villa_05_chef_kitchen.jpg',
    },
    {
      id: 'shot_demo_6',
      project_id: 'proj_kgm_riyadh_01',
      image_id: 'img_demo_6',
      shot_name: 'Primary Sovereign Suite',
      shot_number: 6,
      sequence_order: 6,
      category: 'master_bedroom',
      motion_preset_id: 'preset_bedroom_push',
      camera_movement: 'Slow Forward Push to Terrace',
      camera_direction: 'forward',
      camera_speed: 'slow',
      lens: '35mm',
      lens_focal_length: '35mm',
      duration: 10,
      duration_seconds: 10,
      motion_intensity: 0.15,
      status: 'approved',
      generation_status: 'completed',
      progress: 100,
      provider: 'native_ffmpeg',
      video_url: '/renders/shot_shot_demo_6_master.mp4',
      storage_path: '/uploads/villa_06_master_suite.jpg',
    },
    {
      id: 'shot_demo_7',
      project_id: 'proj_kgm_riyadh_01',
      image_id: 'img_demo_7',
      shot_name: 'Wellness Spa Primary Bath',
      shot_number: 7,
      sequence_order: 7,
      category: 'bathroom',
      motion_preset_id: 'preset_bathroom_pan',
      camera_movement: 'Lateral Drift with Reflection',
      camera_direction: 'right',
      camera_speed: 'ultra_slow',
      lens: '35mm',
      lens_focal_length: '35mm',
      duration: 10,
      duration_seconds: 10,
      motion_intensity: 0.14,
      status: 'approved',
      generation_status: 'completed',
      progress: 100,
      provider: 'native_ffmpeg',
      video_url: '/renders/shot_shot_demo_7_master.mp4',
      storage_path: '/uploads/villa_07_spa_bathroom.jpg',
    },
    {
      id: 'shot_demo_8',
      project_id: 'proj_kgm_riyadh_01',
      image_id: 'img_demo_8',
      shot_name: 'Infinity Pool Oasis & Fire Pit',
      shot_number: 8,
      sequence_order: 8,
      category: 'pool',
      motion_preset_id: 'preset_pool_reveal',
      camera_movement: 'Forward Glide across Waterline',
      camera_direction: 'forward',
      camera_speed: 'slow',
      lens: '24mm',
      lens_focal_length: '24mm',
      duration: 10,
      duration_seconds: 10,
      motion_intensity: 0.28,
      status: 'approved',
      generation_status: 'completed',
      progress: 100,
      provider: 'native_ffmpeg',
      video_url: '/renders/shot_shot_demo_8_master.mp4',
      storage_path: '/uploads/villa_08_infinity_pool.jpg',
    },
    {
      id: 'shot_demo_9',
      project_id: 'proj_kgm_riyadh_01',
      image_id: 'img_demo_9',
      shot_name: 'Private Palm Oasis & Lounge',
      shot_number: 9,
      sequence_order: 9,
      category: 'garden',
      motion_preset_id: 'preset_balcony_pan',
      camera_movement: 'Parallax Pan across Flora',
      camera_direction: 'left',
      camera_speed: 'slow',
      lens: '28mm',
      lens_focal_length: '28mm',
      duration: 10,
      duration_seconds: 10,
      motion_intensity: 0.20,
      status: 'approved',
      generation_status: 'completed',
      progress: 100,
      provider: 'native_ffmpeg',
      video_url: '/renders/shot_shot_demo_9_master.mp4',
      storage_path: '/uploads/villa_09_private_garden.jpg',
    },
    {
      id: 'shot_demo_10',
      project_id: 'proj_kgm_riyadh_01',
      image_id: 'img_demo_10',
      shot_name: 'Twilight Architectural Horizon',
      shot_number: 10,
      sequence_order: 10,
      category: 'exterior',
      motion_preset_id: 'preset_hero_exterior',
      camera_movement: 'Majestic Slow Pull Out & Hold',
      camera_direction: 'backward',
      camera_speed: 'ultra_slow',
      lens: '24mm',
      lens_focal_length: '24mm',
      duration: 10,
      duration_seconds: 10,
      motion_intensity: 0.18,
      status: 'approved',
      generation_status: 'completed',
      progress: 100,
      provider: 'native_ffmpeg',
      video_url: '/renders/shot_shot_demo_10_master.mp4',
      storage_path: '/uploads/villa_10_twilight_hero.jpg',
    },
  ],
  images: [
    { id: 'img_demo_1', project_id: 'proj_kgm_riyadh_01', storage_path: '/uploads/villa_01_hero_exterior.jpg', file_path: '/uploads/villa_01_hero_exterior.jpg', original_filename: 'villa_01_hero_exterior.jpg', sort_order: 1, category: 'exterior', room_category: 'exterior', lighting_condition: 'dusk_golden_hour', confidence: 0.98, detected_features: 'Travertine facade, twilight lighting' },
    { id: 'img_demo_2', project_id: 'proj_kgm_riyadh_01', storage_path: '/uploads/villa_02_entrance_foyer.jpg', file_path: '/uploads/villa_02_entrance_foyer.jpg', original_filename: 'villa_02_entrance_foyer.jpg', sort_order: 2, category: 'entrance', room_category: 'entrance', lighting_condition: 'interior_diffused', confidence: 0.95, detected_features: 'Pivot door, marble foyer' },
    { id: 'img_demo_3', project_id: 'proj_kgm_riyadh_01', storage_path: '/uploads/villa_03_living_salon.jpg', file_path: '/uploads/villa_03_living_salon.jpg', original_filename: 'villa_03_living_salon.jpg', sort_order: 3, category: 'living_room', room_category: 'living_room', lighting_condition: 'natural_daylight', confidence: 0.97, detected_features: 'Double-height glass, bespoke lounge' },
    { id: 'img_demo_4', project_id: 'proj_kgm_riyadh_01', storage_path: '/uploads/villa_04_formal_dining.jpg', file_path: '/uploads/villa_04_formal_dining.jpg', original_filename: 'villa_04_formal_dining.jpg', sort_order: 4, category: 'dining', room_category: 'dining', lighting_condition: 'warm_ambient', confidence: 0.94, detected_features: '12-seat table, crystal chandelier' },
    { id: 'img_demo_5', project_id: 'proj_kgm_riyadh_01', storage_path: '/uploads/villa_05_chef_kitchen.jpg', file_path: '/uploads/villa_05_chef_kitchen.jpg', original_filename: 'villa_05_chef_kitchen.jpg', sort_order: 5, category: 'kitchen', room_category: 'kitchen', lighting_condition: 'integrated_led', confidence: 0.96, detected_features: 'Calacatta marble island, Gaggenau' },
    { id: 'img_demo_6', project_id: 'proj_kgm_riyadh_01', storage_path: '/uploads/villa_06_master_suite.jpg', file_path: '/uploads/villa_06_master_suite.jpg', original_filename: 'villa_06_master_suite.jpg', sort_order: 6, category: 'master_bedroom', room_category: 'master_bedroom', lighting_condition: 'morning_diffused', confidence: 0.95, detected_features: 'Floor-to-ceiling glass, custom headboard' },
    { id: 'img_demo_7', project_id: 'proj_kgm_riyadh_01', storage_path: '/uploads/villa_07_spa_bathroom.jpg', file_path: '/uploads/villa_07_spa_bathroom.jpg', original_filename: 'villa_07_spa_bathroom.jpg', sort_order: 7, category: 'bathroom', room_category: 'bathroom', lighting_condition: 'soft_ambient', confidence: 0.93, detected_features: 'Stone soaking tub, marble shower' },
    { id: 'img_demo_8', project_id: 'proj_kgm_riyadh_01', storage_path: '/uploads/villa_08_infinity_pool.jpg', file_path: '/uploads/villa_08_infinity_pool.jpg', original_filename: 'villa_08_infinity_pool.jpg', sort_order: 8, category: 'pool', room_category: 'pool', lighting_condition: 'golden_hour', confidence: 0.98, detected_features: 'Infinity edge, sunken fire lounge' },
    { id: 'img_demo_9', project_id: 'proj_kgm_riyadh_01', storage_path: '/uploads/villa_09_private_garden.jpg', file_path: '/uploads/villa_09_private_garden.jpg', original_filename: 'villa_09_private_garden.jpg', sort_order: 9, category: 'garden', room_category: 'garden', lighting_condition: 'twilight_ambient', confidence: 0.92, detected_features: 'Manicured palms, perimeter lighting' },
    { id: 'img_demo_10', project_id: 'proj_kgm_riyadh_01', storage_path: '/uploads/villa_10_twilight_hero.jpg', file_path: '/uploads/villa_10_twilight_hero.jpg', original_filename: 'villa_10_twilight_hero.jpg', sort_order: 10, category: 'exterior', room_category: 'exterior', lighting_condition: 'dusk_prestige', confidence: 0.99, detected_features: 'Estate horizon, illuminated pool' },
  ],
  exports: [
    {
      id: 'exp_proj_kgm_riyadh_01_master',
      project_id: 'proj_kgm_riyadh_01',
      render_job_id: 'rend_demo_master_01',
      export_type: 'master_4k',
      title: 'KGM Master Film (16:9 4K / 1080p Cine Master)',
      file_path: '/exports/film_proj_kgm_riyadh_01_master_16x9.mp4',
      file_size: 21600000,
      resolution: '1920x1080',
      aspect_ratio: '16:9',
      download_count: 0,
      created_at: '2026-09-19T12:57:36.247Z',
    },
    {
      id: 'exp_proj_kgm_riyadh_01_portrait',
      project_id: 'proj_kgm_riyadh_01',
      render_job_id: 'rend_demo_master_01',
      export_type: 'social_portrait',
      title: 'Social Portrait (9:16 Instagram Reels / TikTok)',
      file_path: '/exports/film_proj_kgm_riyadh_01_social_portrait_9x16.mp4',
      file_size: 19500000,
      resolution: '1080x1920',
      aspect_ratio: '9:16',
      download_count: 0,
      created_at: '2026-09-19T12:57:36.247Z',
    },
    {
      id: 'exp_proj_kgm_riyadh_01_square',
      project_id: 'proj_kgm_riyadh_01',
      render_job_id: 'rend_demo_master_01',
      export_type: 'social_square',
      title: 'Social Square (1:1 Instagram Post / LinkedIn)',
      file_path: '/exports/film_proj_kgm_riyadh_01_social_square_1x1.mp4',
      file_size: 13000000,
      resolution: '1080x1080',
      aspect_ratio: '1:1',
      download_count: 0,
      created_at: '2026-09-19T12:57:36.247Z',
    },
    {
      id: 'exp_proj_kgm_riyadh_01_wa',
      project_id: 'proj_kgm_riyadh_01',
      render_job_id: 'rend_demo_master_01',
      export_type: 'whatsapp_compressed',
      title: 'WhatsApp Optimized Mobile Share',
      file_path: '/exports/film_proj_kgm_riyadh_01_whatsapp_fast.mp4',
      file_size: 2900000,
      resolution: '1280x720',
      aspect_ratio: '16:9',
      download_count: 0,
      created_at: '2026-09-19T12:57:36.247Z',
    },
  ],
  brand: {
    id: 'brand_kgm_default',
    company_name: 'Kurra Greenfield Merchants Limited (KGM Limited)',
    tagline: 'Private Client Real Estate Cinema & Architectural Marketing',
    primary_color: '#0B2B20',
    secondary_color: '#C5A869',
    accent_color: '#F4EBD9',
    font_heading: 'Cinzel',
    font_body: 'Montserrat',
    show_intro_card: 1,
    show_outro_card: 1,
    intro_duration_seconds: 3.5,
    outro_duration_seconds: 4.5,
    watermark_enabled: 1,
    is_default: 1,
  },
  musicTracks: [
    { id: 'mus_lux_01', title: 'The Sovereign Estate', artist: 'KGM Studio Philharmonic', category: 'classical_prestige', genre: 'Orchestral Cello & Piano', bpm: 68, duration_seconds: 120, file_path: '/audio/luxury_prestige.mp3', is_royalty_verified: 1 },
    { id: 'mus_lux_02', title: 'Royal Estate Horizons', artist: 'Sovereign Acoustic Works', category: 'ambient_strings', genre: 'Warm Strings', bpm: 72, duration_seconds: 120, file_path: '/audio/royal_estate.mp3', is_royalty_verified: 1 },
    { id: 'mus_lux_03', title: 'Reflections in Marble', artist: 'KGM Soundstage', category: 'minimal_piano', genre: 'Acoustic Solo Piano', bpm: 64, duration_seconds: 120, file_path: '/audio/reflections_marble.mp3', is_royalty_verified: 1 },
    { id: 'mus_lux_04', title: 'Emerald Oasis Twilight', artist: 'Arabian Heritage Symphony', category: 'modern_middle_east', genre: 'Oud & Orchestral Drone', bpm: 70, duration_seconds: 120, file_path: '/audio/emerald_oasis.mp3', is_royalty_verified: 1 },
    { id: 'mus_lux_05', title: 'Chamber of Gold', artist: 'KGM Ensemble', category: 'luxury_cinematic', genre: 'Ethereal Cinematic', bpm: 75, duration_seconds: 120, file_path: '/audio/chamber_gold.mp3', is_royalty_verified: 1 },
  ],
  presets: [
    { id: 'preset_hero_exterior', key: 'hero_exterior', name: 'Hero Exterior Slow Dolly', description: 'Majestic forward camera glide towards architectural facade.', camera_movement: 'Dolly In (Forward Axial)', direction: 'forward', speed: 'slow', default_duration: 10, default_lens: '24mm', lens_focal_length: '24mm', motion_intensity: 0.25 },
    { id: 'preset_entrance_foyer', key: 'entrance_foyer', name: 'Grand Entrance Jib Ascent', description: 'Vertical crane tilt revealing double-height foyer and chandelier.', camera_movement: 'Vertical Jib / Crane Up', direction: 'up', speed: 'slow', default_duration: 10, default_lens: '24mm', lens_focal_length: '24mm', motion_intensity: 0.22 },
    { id: 'preset_living_glide', key: 'living_room', name: 'Living Salon Lateral Tracking', description: 'Fluid left-to-right dolly tracking shot through main entertaining room.', camera_movement: 'Lateral Tracking (Left to Right)', direction: 'right', speed: 'slow', default_duration: 10, default_lens: '28mm', lens_focal_length: '28mm', motion_intensity: 0.20 },
    { id: 'preset_dining_sweep', key: 'dining_room', name: 'Dining Salon Diagonal Push', description: 'Diagonal push along banquet table focusing on crystal and lighting.', camera_movement: 'Slow Diagonal Push', direction: 'forward_right', speed: 'slow', default_duration: 10, default_lens: '35mm', lens_focal_length: '35mm', motion_intensity: 0.18 },
    { id: 'preset_kitchen_dolly', key: 'kitchen', name: 'Culinary Island Parallax Drift', description: 'Axial push along monolithic marble island with shallow depth of field.', camera_movement: 'Axial Dolly & Shallow Parallax', direction: 'forward', speed: 'slow', default_duration: 10, default_lens: '35mm', lens_focal_length: '35mm', motion_intensity: 0.18 },
    { id: 'preset_bedroom_push', key: 'master_bedroom', name: 'Primary Suite Horizon Drift', description: 'Slow forward camera push towards floor-to-ceiling panoramic glass.', camera_movement: 'Slow Forward Push to Terrace', direction: 'forward', speed: 'slow', default_duration: 10, default_lens: '35mm', lens_focal_length: '35mm', motion_intensity: 0.15 },
    { id: 'preset_bathroom_pan', key: 'master_bath', name: 'Spa Bathroom Lateral Reflection', description: 'Ultra-slow lateral glide past freestanding soaking tub and marble vanity.', camera_movement: 'Lateral Drift with Reflection', direction: 'right', speed: 'ultra_slow', default_duration: 10, default_lens: '35mm', lens_focal_length: '35mm', motion_intensity: 0.14 },
    { id: 'preset_pool_reveal', key: 'pool_terrace', name: 'Infinity Pool Waterline Glide', description: 'Smooth low-angle forward tracking shot over illuminated pool surface.', camera_movement: 'Forward Glide across Waterline', direction: 'forward', speed: 'slow', default_duration: 10, default_lens: '24mm', lens_focal_length: '24mm', motion_intensity: 0.28 },
    { id: 'preset_balcony_pan', key: 'balcony_terrace', name: 'Oasis Garden Parallax Sweep', description: 'Slow panoramic sweep across manicured palm gardens and exterior lounge.', camera_movement: 'Parallax Pan across Flora', direction: 'left', speed: 'slow', default_duration: 10, default_lens: '28mm', lens_focal_length: '28mm', motion_intensity: 0.20 },
    { id: 'preset_sunset_orbit', key: 'sunset_orbit', name: 'Twilight Skyline Orbit', description: 'Curved orbital wrap embracing twilight architecture and glowing pool edge.', camera_movement: 'Orbital Arc Wrap', direction: 'orbit_cw', speed: 'ultra_slow', default_duration: 10, default_lens: '24mm', lens_focal_length: '24mm', motion_intensity: 0.22 },
  ],
  providers: [
    { id: 'prov_native', provider_type: 'native_neural', name: 'KGM Native Neural Engine (FFmpeg Master)', api_base_url: 'Internal GPU Cluster', monthly_budget_usd: 500, current_balance: 498.50, is_active: 1 },
    { id: 'prov_runway', provider_type: 'runway', name: 'Runway Gen-3 Alpha', api_base_url: 'https://api.runwayml.com/v1', monthly_budget_usd: 2500, current_balance: 2420.00, is_active: 1 },
    { id: 'prov_luma', provider_type: 'luma', name: 'Luma Dream Machine', api_base_url: 'https://api.lumalabs.ai/v1', monthly_budget_usd: 1500, current_balance: 1465.00, is_active: 1 },
    { id: 'prov_kling', provider_type: 'kling', name: 'Kling AI v1.5 Pro', api_base_url: 'https://api.klingai.com/v1', monthly_budget_usd: 1200, current_balance: 1180.00, is_active: 1 },
    { id: 'prov_veo', provider_type: 'google_veo', name: 'Google Veo 2 (Cinematic 4K)', api_base_url: 'https://generativelanguage.googleapis.com/v1beta', monthly_budget_usd: 3000, current_balance: 2980.00, is_active: 1 },
  ],
  users: [
    { id: 'usr_super_01', email: 'director@kgm-estates.com', full_name: 'Alexander Kurra — Executive Creative Director', role: 'super_admin', created_at: '2026-09-19T01:00:00.000Z' },
    { id: 'usr_producer_01', email: 'producer@kgm-estates.com', full_name: 'Elena Vance — Senior Film Producer', role: 'producer', created_at: '2026-09-19T01:00:00.000Z' },
    { id: 'usr_editor_01', email: 'editor@kgm-estates.com', full_name: 'Tariq Mansoor — Master Colorist & Editor', role: 'editor', created_at: '2026-09-19T01:00:00.000Z' },
    { id: 'usr_partner_01', email: 'faris.alsaud@kgm-estates.com', full_name: 'Faris Al-Saud — Senior Managing Partner', role: 'agency_admin', created_at: '2026-09-19T01:00:00.000Z' },
  ],
  recentAudit: [
    { id: 'aud_01', user_id: 'usr_super_01', action: 'film_master_rendered', entity_type: 'project', entity_id: 'proj_kgm_riyadh_01', created_at: '2026-09-19T12:57:36.247Z' },
    { id: 'aud_02', user_id: 'usr_super_01', action: 'shot_approved', entity_type: 'cinematic_shot', entity_id: 'shot_demo_10', created_at: '2026-09-19T12:55:00.000Z' },
    { id: 'aud_03', user_id: 'usr_producer_01', action: 'storyboard_auto_arranged', entity_type: 'project', entity_id: 'proj_kgm_riyadh_01', created_at: '2026-09-19T12:45:00.000Z' },
    { id: 'aud_04', user_id: 'usr_super_01', action: 'project_created', entity_type: 'project', entity_id: 'proj_kgm_riyadh_01', created_at: '2026-09-19T01:03:14.298Z' },
  ],
};
